# Generated by Django 2.2.3 on 2020-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='中文名')),
                ('pub_date', models.CharField(max_length=32, verbose_name='发布时间')),
                ('movie_type', models.CharField(max_length=32, verbose_name='类型')),
                ('source', models.CharField(max_length=64, verbose_name='来源')),
                ('distributor', models.CharField(max_length=64, verbose_name='发行商')),
                ('uri', models.CharField(max_length=128, unique=True, verbose_name='URI')),
                ('director_uri', models.CharField(max_length=128, verbose_name='导演')),
                ('actors_uri', models.CharField(max_length=1024, verbose_name='演员')),
                ('screen_writer_uri', models.CharField(max_length=128, verbose_name='编剧')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='MoviePeople',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=128, unique=True, verbose_name='URI')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '艺人',
                'verbose_name_plural': '艺人',
            },
        ),
    ]
