# Generated by Django 2.2.3 on 2020-06-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0004_auto_20200623_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviephoto',
            name='movieUri',
            field=models.CharField(max_length=128, null=True, verbose_name='电影URI'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=64, verbose_name='电影名'),
        ),
    ]
