# Generated by Django 2.2.3 on 2020-06-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0005_auto_20200630_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(default='', max_length=128, verbose_name='类型'),
        ),
    ]
