# Generated by Django 2.2.3 on 2020-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0006_auto_20200630_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePhotoRelation',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('photoUri', models.CharField(max_length=128, verbose_name='剧照URI')),
                ('relationUri', models.CharField(max_length=128, verbose_name='关系URI')),
                ('relationName', models.CharField(max_length=128, null=True, verbose_name='关系名称')),
                ('relationType', models.CharField(max_length=32, verbose_name='关系类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '照片关系',
                'verbose_name_plural': '照片关系',
            },
        ),
        migrations.AlterModelOptions(
            name='moviephoto',
            options={'verbose_name': '电影照片', 'verbose_name_plural': '电影照片'},
        ),
        migrations.AddField(
            model_name='moviephoto',
            name='movieName',
            field=models.CharField(max_length=128, null=True, verbose_name='电影名称'),
        ),
        migrations.AddField(
            model_name='moviephoto',
            name='photo_date',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
    ]
