# Generated by Django 2.2.3 on 2020-07-04 17:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0007_auto_20200630_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCinema',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='影院名称')),
                ('nameEn', models.CharField(max_length=64, verbose_name='英文名')),
                ('uri', models.CharField(max_length=128, unique=True, verbose_name='URI')),
                ('architectureUri', models.CharField(max_length=128, verbose_name='建筑URI')),
                ('des', models.CharField(max_length=256, verbose_name='描述')),
                ('raw', django_mysql.models.JSONField(default=dict, null=True, verbose_name='元数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '影院',
                'verbose_name_plural': '电影院',
            },
        ),
        migrations.CreateModel(
            name='MoviePhotoPeople',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('photoUri', models.CharField(max_length=128, verbose_name='剧照URI')),
                ('peopleUri', models.CharField(max_length=128, verbose_name='关系URI')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '照片人物关系',
                'verbose_name_plural': '照片人物关系',
                'unique_together': {('photoUri', 'peopleUri')},
            },
        ),
        migrations.DeleteModel(
            name='MoviePhotoRelation',
        ),
        migrations.AlterField(
            model_name='moviephoto',
            name='movieUri',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='电影URI'),
        ),
    ]
