# Generated by Django 2.2.3 on 2020-07-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0009_auto_20200705_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to='movie/movies/', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='moviecinema',
            name='image',
            field=models.ImageField(null=True, upload_to='movie/cinemas/', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='moviepeople',
            name='image',
            field=models.ImageField(null=True, upload_to='movie/peoples/', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='moviephoto',
            name='cinemaName',
            field=models.CharField(max_length=128, null=True, verbose_name='影院名称'),
        ),
        migrations.AddField(
            model_name='moviephoto',
            name='cinemaUri',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='影院URI'),
        ),
        migrations.AddField(
            model_name='moviephotopeople',
            name='peopleName',
            field=models.CharField(default=None, max_length=128, verbose_name='影人姓名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviephotopeople',
            name='peopleUri',
            field=models.CharField(max_length=128, verbose_name='影人URI'),
        ),
    ]
