# Generated by Django 2.2.3 on 2020-07-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0010_auto_20200706_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecinema',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='moviecinema',
            name='latitude_bmap',
            field=models.FloatField(null=True, verbose_name='纬度(百度地图)'),
        ),
        migrations.AddField(
            model_name='moviecinema',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='moviecinema',
            name='longitude_bmap',
            field=models.FloatField(null=True, verbose_name='经度(百度地图)'),
        ),
    ]
