# Generated by Django 2.2.3 on 2020-07-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0012_movie_formated_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/movies/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='moviecinema',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/cinemas/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='moviecinema',
            name='uri',
            field=models.CharField(blank=True, max_length=128, unique=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='moviepeople',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie/peoples/', verbose_name='图片'),
        ),
    ]
