# Generated by Django 2.2.3 on 2020-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0015_auto_20200709_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='des',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='moviecinema',
            name='build_date',
            field=models.CharField(blank=True, max_length=64, verbose_name='建造时间'),
        ),
    ]
