# Generated by Django 2.2.3 on 2020-07-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0017_auto_20200715_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='lib_image_path',
            field=models.URLField(default=None, null=True, verbose_name='爬取图片'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='formated_pub_date',
            field=models.IntegerField(default=0, verbose_name='格式化的发布时间'),
        ),
    ]
