# Generated by Django 2.2.3 on 2020-07-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0018_auto_20200715_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='event_count',
            field=models.IntegerField(default=0, verbose_name='事件个数'),
        ),
        migrations.AddField(
            model_name='moviepeople',
            name='event_count',
            field=models.IntegerField(default=0, verbose_name='事件个数'),
        ),
        migrations.AddField(
            model_name='moviepeople',
            name='movie_count',
            field=models.IntegerField(default=0, verbose_name='作品个数'),
        ),
    ]
