# Generated by Django 3.0.8 on 2020-07-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0020_auto_20200721_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepeoplerelation',
            name='is_director',
        ),
        migrations.AddField(
            model_name='moviepeoplerelation',
            name='rule_type',
            field=models.CharField(default=False, max_length=64, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='moviepeoplerelation',
            name='movie_uri',
            field=models.CharField(max_length=128, unique=True, verbose_name='电影URI'),
        ),
        migrations.AlterField(
            model_name='moviepeoplerelation',
            name='people_uri',
            field=models.CharField(max_length=128, unique=True, verbose_name='影人URI'),
        ),
    ]
