# Generated by Django 3.0.8 on 2020-07-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddmovie', '0022_moviecinema_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepeople',
            name='des',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
    ]
