# Generated by Django 2.2.1 on 2019-07-13 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_cht', models.CharField(max_length=64, unique=True, verbose_name='繁体名')),
                ('name_chs', models.CharField(max_length=64, null=True, verbose_name='简体名')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='英文名')),
                ('houseNumber', models.CharField(max_length=16, null=True, verbose_name='房间号')),
                ('address', models.CharField(max_length=256, null=True, verbose_name='地址')),
                ('longitude', models.FloatField(null=True, verbose_name='经度')),
                ('latitude', models.FloatField(null=True, verbose_name='纬度')),
                ('place_uri', models.URLField(null=True, verbose_name='所在区URI')),
                ('place_name', models.CharField(max_length=64, null=True, verbose_name='所在区')),
                ('des', models.TextField(null=True, verbose_name='简介(上海图书馆数据)')),
                ('des2', models.TextField(null=True, verbose_name='简介(手动编辑)')),
                ('first_image_uri', models.URLField(null=True, verbose_name='首页照片URI')),
                ('first_image_path', models.ImageField(null=True, upload_to='pic/architecture_first/')),
                ('batch_no', models.CharField(max_length=16, null=True, verbose_name='批次')),
                ('protect_type', models.CharField(max_length=16, null=True, verbose_name='保护类型')),
                ('is_from_lib', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_chs', models.CharField(max_length=64, unique=True, verbose_name='现路名')),
                ('name_en', models.CharField(max_length=64, null=True, verbose_name='英文名')),
                ('temporal_value', models.CharField(max_length=64, null=True, verbose_name='开始/结束时间')),
                ('history_of_name', models.CharField(max_length=64, null=True, verbose_name='历史路名')),
                ('name_after', models.CharField(max_length=64, null=True, verbose_name='以..命名')),
                ('uri', models.URLField(null=True, verbose_name='URI')),
                ('history_of', models.URLField(null=True, verbose_name='历史关联URI')),
                ('des', models.TextField(null=True, verbose_name='简介(上海图书馆数据)')),
                ('des2', models.TextField(null=True, verbose_name='简介(手动编辑)')),
                ('place_uri', models.URLField(null=True, verbose_name='所在区URI')),
                ('place_name', models.CharField(max_length=64, null=True, verbose_name='所在区')),
                ('is_from_lib', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArchitecturePicture',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('pic_uri', models.URLField(null=True)),
                ('pic_format', models.CharField(max_length=16, null=True)),
                ('pic_file', models.ImageField(null=True, upload_to='pic/architecture/')),
                ('des', models.TextField(null=True, verbose_name='简介(上海图书馆数据)')),
                ('des2', models.TextField(null=True, verbose_name='简介(手动编辑)')),
                ('is_from_lib', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddsrc.Architecture')),
            ],
        ),
        migrations.AddField(
            model_name='architecture',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddsrc.Road'),
        ),
    ]
