# Generated by Django 2.2.1 on 2019-07-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0002_auto_20190713_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='road_lib_uri',
            field=models.URLField(null=True, verbose_name='马路URI'),
        ),
    ]
