# Generated by Django 2.2.1 on 2019-07-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0004_auto_20190714_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='road_name_chs',
            field=models.CharField(max_length=64, null=True, verbose_name='马路简体名'),
        ),
    ]
