# Generated by Django 2.2.1 on 2019-07-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0005_architecture_road_name_chs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='road',
            old_name='history_of',
            new_name='history_of_lib_uri',
        ),
    ]
