# Generated by Django 2.2.1 on 2019-07-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0006_auto_20190714_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architecture',
            options={'verbose_name': '优秀历史建筑', 'verbose_name_plural': '优秀历史建筑'},
        ),
        migrations.AlterModelOptions(
            name='architecturepicture',
            options={'verbose_name': '优秀历史建筑图片', 'verbose_name_plural': '优秀历史建筑图片'},
        ),
        migrations.AlterModelOptions(
            name='road',
            options={'verbose_name': '马路', 'verbose_name_plural': '马路'},
        ),
        migrations.AlterField(
            model_name='architecture',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='house_number',
            field=models.CharField(max_length=64, null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='lib_update_time',
            field=models.DateTimeField(null=True, verbose_name='数据获取时间'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='architecturepicture',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='architecturepicture',
            name='lib_update_time',
            field=models.DateTimeField(null=True, verbose_name='数据获取时间'),
        ),
        migrations.AlterField(
            model_name='architecturepicture',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='road',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='road',
            name='history_of_name',
            field=models.CharField(max_length=64, null=True, verbose_name='历史'),
        ),
        migrations.AlterField(
            model_name='road',
            name='lib_update_time',
            field=models.DateTimeField(null=True, verbose_name='数据获取时间'),
        ),
        migrations.AlterField(
            model_name='road',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
