# Generated by Django 2.2.1 on 2019-07-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0009_auto_20190715_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='house_number',
            field=models.CharField(max_length=256, null=True, verbose_name='房间号'),
        ),
    ]
