# Generated by Django 2.2.1 on 2019-07-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0011_auto_20190719_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='protect_type',
            field=models.CharField(max_length=128, null=True, verbose_name='保护类型'),
        ),
    ]
