# Generated by Django 2.2.1 on 2019-07-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0012_auto_20190719_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='name_chs',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='简体名'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='name_cht',
            field=models.CharField(max_length=64, null=True, verbose_name='繁体名'),
        )
    ]
