# Generated by Django 2.2.1 on 2019-07-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0013_auto_20190720_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architecture',
            options={'verbose_name': '建筑', 'verbose_name_plural': '建筑'},
        ),
    ]
