# Generated by Django 2.2.1 on 2019-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0014_auto_20190720_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='latitude_bmap',
            field=models.FloatField(null=True, verbose_name='纬度(百度地图)'),
        ),
        migrations.AddField(
            model_name='architecture',
            name='longitude_bmap',
            field=models.FloatField(null=True, verbose_name='经度(百度地图)'),
        ),
        migrations.AddField(
            model_name='road',
            name='latitude_bmap',
            field=models.FloatField(null=True, verbose_name='纬度(百度地图)'),
        ),
        migrations.AddField(
            model_name='road',
            name='longitude_bmap',
            field=models.FloatField(null=True, verbose_name='经度(百度地图)'),
        ),
    ]
