# Generated by Django 2.2.1 on 2019-07-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0016_auto_20190725_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='place_name2',
            field=models.CharField(max_length=64, null=True, verbose_name='所在区(手动编辑)'),
        ),
    ]
