# Generated by Django 2.2.1 on 2019-07-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0018_auto_20190725_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='latitude_gaode',
            field=models.FloatField(null=True, verbose_name='纬度(高德地图)'),
        ),
        migrations.AddField(
            model_name='road',
            name='longitude_gaode',
            field=models.FloatField(null=True, verbose_name='经度(高德地图)'),
        ),
        migrations.AddField(
            model_name='road',
            name='polylines_bmap',
            field=models.CharField(max_length=1024, null=True, verbose_name='坐标点(百度地图)'),
        ),
        migrations.AddField(
            model_name='road',
            name='polylines_gaode',
            field=models.CharField(max_length=1024, null=True, verbose_name='坐标点(高德地图)'),
        ),
    ]
