# Generated by Django 2.2.1 on 2019-07-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0019_auto_20190726_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='road',
            name='latitude_bmap',
        ),
        migrations.RemoveField(
            model_name='road',
            name='latitude_gaode',
        ),
        migrations.RemoveField(
            model_name='road',
            name='longitude_bmap',
        ),
        migrations.RemoveField(
            model_name='road',
            name='longitude_gaode',
        ),
        migrations.RemoveField(
            model_name='road',
            name='polylines_bmap',
        ),
        migrations.RemoveField(
            model_name='road',
            name='polylines_gaode',
        ),
    ]
