# Generated by Django 2.2.1 on 2019-07-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0021_auto_20190726_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='center_bmap',
            field=models.TextField(default='', null=True, verbose_name='中心坐标点(百度地图)'),
        ),
        migrations.AddField(
            model_name='road',
            name='center_gaode',
            field=models.TextField(default='', null=True, verbose_name='中心坐标点(高德地图)'),
        ),
        migrations.AlterField(
            model_name='road',
            name='polylines_bmap',
            field=models.TextField(default='', null=True, verbose_name='折线坐标集(百度地图)'),
        ),
        migrations.AlterField(
            model_name='road',
            name='polylines_gaode',
            field=models.TextField(default='', null=True, verbose_name='折线坐标集(高德地图)'),
        ),
    ]
