# Generated by Django 2.2.1 on 2019-07-29 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0022_auto_20190728_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='road',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_architecture', to='ddsrc.Road'),
        ),
    ]
