# Generated by Django 2.2.1 on 2019-08-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0024_auto_20190807_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='name_chs',
            field=models.CharField(db_index=True, max_length=64, null=True, unique=True, verbose_name='简体名'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='road_name_chs',
            field=models.CharField(db_index=True, max_length=64, null=True, verbose_name='马路简体名'),
        ),
        migrations.AlterField(
            model_name='road',
            name='name_chs',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='中文名'),
        ),
    ]
