# Generated by Django 2.2.3 on 2020-05-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0025_auto_20190809_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='center_bmap',
            field=models.TextField(null=True, verbose_name='中心坐标点(百度地图)'),
        ),
        migrations.AlterField(
            model_name='road',
            name='center_gaode',
            field=models.TextField(null=True, verbose_name='中心坐标点(高德地图)'),
        ),
        migrations.AlterField(
            model_name='road',
            name='polylines_bmap',
            field=models.TextField(null=True, verbose_name='折线坐标集(百度地图)'),
        ),
        migrations.AlterField(
            model_name='road',
            name='polylines_gaode',
            field=models.TextField(null=True, verbose_name='折线坐标集(高德地图)'),
        ),
    ]
