# Generated by Django 2.2.3 on 2020-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0027_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_uri',
            new_name='uri',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_begin',
            field=models.DateTimeField(null=True, verbose_name='事件开始事件'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(null=True, verbose_name='事件结束事件'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_title',
            field=models.CharField(max_length=128, null=True, verbose_name='事件名称'),
        ),
    ]
