# Generated by Django 2.2.3 on 2020-06-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0028_auto_20200630_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_begin',
            field=models.DateField(null=True, verbose_name='事件开始事件'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateField(null=True, verbose_name='事件结束事件'),
        ),
    ]
