# Generated by Django 2.2.3 on 2020-07-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0029_auto_20200630_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(null=True, upload_to='pic/event/', verbose_name='事件图片'),
        ),
    ]
