# Generated by Django 2.2.3 on 2020-07-08 15:32

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0032_auto_20200707_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRelation',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_uri', models.URLField(null=True, unique=True, verbose_name='事件URI')),
                ('relation_uri', models.URLField(null=True, unique=True, verbose_name='关系URI')),
                ('relation_label', models.CharField(max_length=128, null=True, verbose_name='关系类型')),
                ('relation_type', models.CharField(max_length=32, null=True, verbose_name='关系类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '事件关系',
                'verbose_name_plural': '事件关系',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(null=True, verbose_name='事件描述'),
        ),
        migrations.AddField(
            model_name='event',
            name='detail_raw',
            field=django_mysql.models.JSONField(default=dict, null=True, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='event',
            name='uri',
            field=models.URLField(null=True, unique=True, verbose_name='事件URI'),
        ),
    ]
