# Generated by Django 2.2.3 on 2020-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0033_auto_20200708_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrelation',
            name='event_uri',
            field=models.URLField(null=True, verbose_name='事件URI'),
        ),
        migrations.AlterField(
            model_name='eventrelation',
            name='relation_uri',
            field=models.URLField(null=True, verbose_name='关系URI'),
        ),
        migrations.AlterUniqueTogether(
            name='eventrelation',
            unique_together={('event_uri', 'relation_uri')},
        ),
    ]
