# Generated by Django 2.2.3 on 2020-07-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0034_auto_20200708_2358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventrelation',
            unique_together={('event_uri', 'relation_uri', 'relation_type', 'relation_label')},
        ),
    ]
