# Generated by Django 2.2.3 on 2020-07-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0037_auto_20200714_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='lib_uri',
            field=models.URLField(blank=True, null=True, verbose_name='URI'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='road_lib_uri',
            field=models.URLField(blank=True, null=True, verbose_name='马路URI'),
        ),
    ]
