# Generated by Django 2.2.3 on 2020-07-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0038_auto_20200720_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='protect_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='保护类型'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_architecture', to='ddsrc.Road'),
        ),
    ]
