# Generated by Django 2.2.3 on 2020-07-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0039_auto_20200720_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='architecture',
            name='road_name_chs',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='马路简体名'),
        ),
    ]
