# Generated by Django 2.2.3 on 2020-07-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsrc', '0040_auto_20200720_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='event_count',
            field=models.IntegerField(default=0, verbose_name='事件个数'),
        ),
    ]
