# Generated by Django 2.2.3 on 2020-07-13 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPath',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='路线名称')),
                ('method', models.CharField(max_length=128, verbose_name='交通工具')),
                ('duration', models.CharField(max_length=128, verbose_name='游览时长')),
                ('feature', models.CharField(max_length=128, verbose_name='路线特色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '路线',
                'verbose_name_plural': '路线',
            },
        ),
        migrations.CreateModel(
            name='TravelPathPoint',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='路线点名称')),
                ('distance', models.CharField(max_length=128, verbose_name='距离')),
                ('duration', models.CharField(max_length=128, verbose_name='浏览时间')),
                ('highlight', models.CharField(max_length=128, verbose_name='亮点')),
                ('is_cinema', models.BooleanField(default=False, verbose_name='是否是影院')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('travel_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddextra.TravelPath')),
            ],
            options={
                'verbose_name': '路线点',
                'verbose_name_plural': '路线点',
            },
        ),
    ]
