# Generated by Django 2.2.3 on 2020-07-14 02:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddextra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichTextArticle',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='文章名称')),
                ('body', ckeditor.fields.RichTextField(verbose_name='文章内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
