# Generated by Django 2.2.3 on 2020-07-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddextra', '0003_auto_20200714_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='richtextarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pic/richtext/'),
        ),
        migrations.AddField(
            model_name='travelpath',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pic/travelpath/'),
        ),
    ]
