# Generated by Django 2.2.3 on 2020-07-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddextra', '0004_auto_20200715_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpathpoint',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='travelpathpoint',
            name='architecture_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='建筑id'),
        ),
        migrations.AddField(
            model_name='travelpathpoint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pic/travelpathpoint/'),
        ),
    ]
