# Generated by Django 3.0.8 on 2020-07-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddextra', '0005_auto_20200720_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpathpoint',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
