# Generated by Django 3.0.8 on 2020-07-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddextra', '0006_travelpathpoint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpath',
            name='latitude',
            field=models.FloatField(default=0.0, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='travelpath',
            name='longitude',
            field=models.FloatField(default=0.0, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='travelpathpoint',
            name='latitude',
            field=models.FloatField(default=0.0, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='travelpathpoint',
            name='longitude',
            field=models.FloatField(default=0.0, null=True, verbose_name='经度'),
        ),
    ]
