# Generated by Django 3.0.8 on 2020-07-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpeotry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peotry',
            options={'verbose_name': '对诗', 'verbose_name_plural': '对诗'},
        ),
        migrations.AddField(
            model_name='peotry',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peotry',
            name='taskId',
            field=models.CharField(default='', max_length=256, verbose_name='taskId'),
        ),
        migrations.AlterField(
            model_name='peotry',
            name='firstWord',
            field=models.CharField(max_length=64, unique=True, verbose_name='输入'),
        ),
        migrations.AlterField(
            model_name='peotry',
            name='result',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='输出'),
        ),
    ]
