# Generated by Django 3.0.9 on 2020-08-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddpeotry', '0002_auto_20200730_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeotryBackground',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie/peoples/', verbose_name='背景图片')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='movie/peoples/', verbose_name='二维码图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '背景图片',
                'verbose_name_plural': '背景图片',
            },
        ),
        migrations.AlterField(
            model_name='peotry',
            name='firstWord',
            field=models.CharField(max_length=64, verbose_name='输入'),
        ),
    ]
