"""
Django settings for ddproj project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/ent/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import socket

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u73)$u^l*_qx)^^^-_m*kl(s+z$w^8riu7d)8uba%-r@2_ygx='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_mysql',
    'rest_framework',
    'django_filters',
    'ddsrc'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'ddproj.urls'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'PAGE_SIZE': 10
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ddproj.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_URL = '/backend/static/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "ddfront/dist/static"),
# ]
       
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ddproj',
        'USER': 'ddxyz',
        'PASSWORD': 'ddpassword',
        'HOST': '192.168.99.102',
        'PORT': '32000',
        'OPTIONS': {
            'charset': 'utf8mb4'
        },
    }
}

SHANGHAI_LIBRARY_API_KEY = '3f5df65840c93fea3c1026b8a64649dffa3d6328'
BAIDU_MAP_JSAPI_KEY = 'bRrHftKV7wBPHYFSkp2GRZQCVGbz8nhy'
GAODE_MAP_WEBAPI_KEY = '82455bd226d65b5c36768ad1cd410fea'

ALLOWED_HOSTS = ["*"]
CORS_ORIGIN_WHITELIST = [
    "http://127.0.0.1:8080",
    "http://localhost:8080",
    "http://dev.datadude.xyz:8080"
]
STATIC_ROOT = os.path.join(BASE_DIR, 'collected_static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# STATIC_URL = '/static/'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AWS_ACCESS_KEY_ID='AKIA564S4C36TY524PYP'
AWS_SECRET_ACCESS_KEY='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'
AWS_STORAGE_BUCKET_NAME='staticfiles.datadude.xyz'
AWS_LOCATION='shlibdev/'
AWS_S3_CUSTOM_DOMAIN = 'staticfiles.datadude.xyz'
AWS_DEFAULT_ACL = None
AWS_HEADERS = {
    'Access-Control-Allow-Origin': '*'
}

STATIC_URL='/shlibdev/'


# if socket.gethostname() == 'ip-172-31-44-132':
#     DEBUG = False
#     ALLOWED_HOSTS = [
#         "api.datadude.xyz",
#         "api2.datadude.xyz"
#     ]
#     CORS_ORIGIN_WHITELIST = [
#         "http://datadude.xyz",
#         "https://datadude.xyz",
#         "http://www.datadude.xyz",
#         "https://www.datadude.xyz",
#         "http://shlib.datadude.xyz",
#         "https://shlib.datadude.xyz"
#     ]
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': 'ddproj',
#             'USER': 'ddxyz',
#             'PASSWORD': 'dDxYz1@3#e',
#             'HOST': 'kr1.cakrcyzdnyyv.ap-northeast-2.rds.amazonaws.com',
#             'PORT': '3306',
#             'OPTIONS': {
#                 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#                 'charset': 'utf8mb4',
#                 'connect_timeout': 5
#             },
#         }
#     }
#     DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#     STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#     AWS_ACCESS_KEY_ID='AKIA564S4C36TY524PYP'
#     AWS_SECRET_ACCESS_KEY='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'
#     AWS_STORAGE_BUCKET_NAME='staticfiles.datadude.xyz'
#     AWS_LOCATION='shlib/'
#     AWS_S3_CUSTOM_DOMAIN = 'staticfiles.datadude.xyz'
#     STATIC_URL='/shlib/'
#     STATIC_ROOT = '/home/ubuntu/collected_static/'
#     MEDIA_ROOT = '/home/ubuntu/media/'
#     MEDIA_URL = '/backend/media/'