version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: 'ddproj'
      MYSQL_USER: 'ddxyz'
      MYSQL_PASSWORD: 'dDxYz1@3#e'
      MYSQL_ROOT_PASSWORD: 'dDxYz1@3#e'
    volumes:
      - ./database:/var/lib/mysql/:rw
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  app:
    build: ../..
    restart: always
    environment:
      - DD_BACKEND_ENV=PROD
    depends_on:
      - mysql
    volumes:
      - ./logs/app:/app/logs/
    ports:
      - "8080:8080"
    links:
      - "mysql"
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx/
    depends_on:
       - app
    links:
      - "app"
