version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: 'ddproj'
      MYSQL_USER: 'ddxyz'
      MYSQL_PASSWORD: 'dDxYz1@3#e'
      MYSQL_ROOT_PASSWORD: 'dDxYz1@3#e'
    volumes:
      - ./database:/var/lib/mysql/:rw
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-rc
    restart: always
    expose:
      - 5672
      - 15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=t11sIs76L
  app:
    build: ../..
    restart: always
    environment:
      - DD_BACKEND_ENV=PROD
    depends_on:
      - mysql
    volumes:
      - /root/peotry_data:/app/data/
      - ./logs/app:/app/logs/
    ports:
      - "8080:8080"
    links:
      - "mysql"
      - "rabbitmq"
  celery_worker:
    build: ../..
    restart: always
    environment:
      - DD_BACKEND_ENV=PROD
    command: sh -c "celery -A ddproj worker -l info"
    volumes:
      - /root/util_data:/app/data/
    depends_on:
      - app
      - mysql
      - rabbitmq
    links:
      - "mysql"