version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: 'ddproj'
      MYSQL_USER: 'ddxyz'
      MYSQL_PASSWORD: 'dDxYz1@3#e'
      MYSQL_ROOT_PASSWORD: 'dDxYz1@3#e'
    volumes:
      - ./database:/var/lib/mysql/:rw
      - ./logs/app:/logs/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
  app:
    build: ../..
    restart: always
    environment:
      - DD_BACKEND_ENV=PROD
    depends_on:
      - mysql
    volumes:
      - ./logs/app:/app/logs/
    ports:
      - "8080:8080"
    links:
      - "mysql"
